# Generated by Django 5.0.14 on 2025-04-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
